OnlineBankingSystem/Models/savingsaccount.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class savingsaccount
    {
        public int accountId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> AdharNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string Landmark { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string OccupationType { get; set; }
        public string Sourceincome { get; set; }
        public Nullable<decimal> Grossalary { get; set; }
    }
}

OnlineBankingSystem/Controllers/AccountDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineBankingSystem.Models;

namespace OnlineBankingSystem.Controllers
{
    public class AccountDetailsController : Controller
    {
        private OnlineBankEntities2 db = new OnlineBankEntities2();

        // GET: AccountDetails
        public ActionResult AccountDetails()
        {
            return View(db.savingsaccounts.ToList());
        }

        // GET: AccountDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            savingsaccount savingsaccount = db.savingsaccounts.Find(id);
            if (savingsaccount == null)
            {
                return HttpNotFound();
            }
            return View(savingsaccount);
        }

        // GET: AccountDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AccountDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "accountId,Title,FirstName,MiddleName,LastName,FatherName,Mobile,Email,AdharNo,DOB,Addressline1,Addressline2,Landmark,State,City,Pincode,OccupationType,Sourceincome,Grossalary")] savingsaccount savingsaccount)
        {
            if (ModelState.IsValid)
            {
                db.savingsaccounts.Add(savingsaccount);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(savingsaccount);
        }

        // GET: AccountDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            savingsaccount savingsaccount = db.savingsaccounts.Find(id);
            if (savingsaccount == null)
            {
                return HttpNotFound();
            }
            return View(savingsaccount);
        }

        // POST: AccountDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "accountId,Title,FirstName,MiddleName,LastName,FatherName,Mobile,Email,AdharNo,DOB,Addressline1,Addressline2,Landmark,State,City,Pincode,OccupationType,Sourceincome,Grossalary")] savingsaccount savingsaccount)
        {
            if (ModelState.IsValid)
            {
                db.Entry(savingsaccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(savingsaccount);
        }

        // GET: AccountDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            savingsaccount savingsaccount = db.savingsaccounts.Find(id);
            if (savingsaccount == null)
            {
                return HttpNotFound();
            }
            return View(savingsaccount);
        }

        // POST: AccountDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            savingsaccount savingsaccount = db.savingsaccounts.Find(id);
            db.savingsaccounts.Remove(savingsaccount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineBankingSystem/Controllers/SavingsaccountController.cs
using OnlineBankingSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OnlineBankingSystem.Controllers
{
    public class SavingsaccountController : Controller
    {
        OnlineBankEntities2 dbModel = new OnlineBankEntities2();
        // GET: Transfer

        [Authorize]
        [HttpGet]
        public ActionResult SavingsAccount()
        {
            savingsaccount sa = new savingsaccount();

            return View(sa);
        }

        [HttpPost]
        public ActionResult SavingsAccount(savingsaccount Model)
        {
            dbModel.savingsaccounts.Add(Model);
            dbModel.SaveChanges();

            ModelState.Clear();
            ViewBag.SuccessMessage = "Your transfer Details Added Succesfully.";
            return RedirectToAction("AccountDetails");
        }

        public ActionResult AccountDetails()
        {
            var fetch = dbModel.savingsaccounts.ToList();

            return View(fetch);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var obj = dbModel.savingsaccounts.Single(x => x.accountId == id);

            return View(obj);
        }

        [HttpPost]
        public ActionResult Edit(savingsaccount sa)
        {
            if (ModelState.IsValid)
            {
                dbModel.Entry(sa).State = EntityState.Modified;
                dbModel.SaveChanges();
                return RedirectToAction("AccountDetails");
            }

            return View(sa);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var obj = dbModel.savingsaccounts.Single(x => x.accountId == id);
            dbModel.savingsaccounts.Remove(obj);
            dbModel.SaveChanges();
            return RedirectToAction("AccountDetails");
        }

      /*  [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var obj = dbModel.savingsaccounts.Single(x => x.accountId == id);
            dbModel.savingsaccounts.Remove(obj);
            dbModel.SaveChanges();

            return RedirectToAction("Index");
        }
*/

        public ActionResult Details(int accountId)
        {
            var obj = dbModel.savingsaccounts.Find();

            return View(obj);
        }

    }
}

OnlineBankingSystem/Views/Savingsaccount/AccountDetails.cshtml
@model IEnumerable<OnlineBankingSystem.Models.savingsaccount>

@{
    ViewBag.Title = "AccountDetails";
}

@*<link href="~/Content/css/form.css" rel="stylesheet" type="text/css" />*@

<h2>Account Details</h2>


<p>
    @Html.ActionLink("Create New", "Savingsaccount/SavingsAccount")
</p>

<head>
    @*<link rel="stylesheet" href="~/Content/css/table.css" type="text/css" />*@
</head>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-condensed table-responsive">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FatherName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdharNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addressline1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addressline2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Landmark)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pincode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OccupationType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sourceincome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grossalary)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MiddleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FatherName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mobile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdharNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DOB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Addressline1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Addressline2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Landmark)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pincode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OccupationType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sourceincome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grossalary)
                </td>
                <td class="btn">
                    @Html.ActionLink("Edit", "Edit", new { id = item.accountId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.accountId })
                </td>
            </tr>
        }

    </table>
</div>

<div>
    @*@Html.ActionLink("back to Dashboard", "Dashboard")*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Back to Dashboard</a>
</div>

<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/bootstrap.js"></script>

OnlineBankingSystem/Views/Savingsaccount/Delete.cshtml
@model OnlineBankingSystem.Models.savingsaccount

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>savingsaccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdharNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdharNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addressline1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addressline1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addressline2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addressline2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Landmark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Landmark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OccupationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OccupationType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sourceincome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sourceincome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grossalary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grossalary)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineBankingSystem/Views/Savingsaccount/Details.cshtml
@model OnlineBankingSystem.Models.savingsaccount

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>savingsaccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdharNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdharNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addressline1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addressline1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addressline2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addressline2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Landmark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Landmark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OccupationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OccupationType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sourceincome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sourceincome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grossalary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grossalary)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.accountId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineBankingSystem/Views/Savingsaccount/SavingsAccount.cshtml
@model OnlineBankingSystem.Models.savingsaccount
@{
    ViewBag.Title = "SavingsAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/css/form.css" rel="stylesheet" type="text/css" />

<h2 class="text-info">SavingsAccount</h2>

@using (Html.BeginForm("SavingsAccount", "Savingsaccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <h4 class="text-info">Create an account for Internet banking.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.MiddleName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.MiddleName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.FatherName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FatherName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Mobile, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Mobile, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.AdharNo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.AdharNo, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.DOB, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.DOB, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Addressline1, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Addressline1, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Addressline2, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Addressline2, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Landmark, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Landmark, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.State, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.City, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Pincode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Pincode, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.OccupationType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.OccupationType, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Sourceincome, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Sourceincome, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group text-info">
        @Html.LabelFor(m => m.Grossalary, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Grossalary, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
    </div>

    <div class="form-group text-info">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-success">@ViewBag.SuccessMessage</label>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}